### ISSUE TITLE
Целесообразность данного проекта

### ISSUE THREAD

**Issue by xllifi** [Russian-Translations-and-Fixes/RTF#1]
Какой в этом смысл?
Не в переводах, а в ресурспаке. Можно же просто открыть PR на гитхабе мода, чтобы твой перевод добавили в мод официально. Есть исключения, но как правило все принимают переводы

**Comment by Exelerium** [comment]
Для такого рода вопросов есть как минимум Discord проекта, но уж точно их надо задавать не на GitHub.

**Comment by xllifi** [comment]
Ну, вопрос я уже задал. Ответ будет?

**Comment by Exelerium** [comment]
Изначально переводы делались исключительно для себя, а дальше уже получилось как есть. Именно такой формат был выбран в первую очередь из-за удобства и нежелания "бегать" за каждым разработчиком. Не с каждым разработчиком есть возможность связаться и не у каждого проекта есть GitHub, куда можно было бы предложить перевод. Разработчики крайне неохотно добавляют переводы в свои модификации, некоторые висят в пулрекестах годами, в лучших случаях месяцами. Подобный формат позволяет этого избежать полностью, давая возможность переводить, дополнять и исправлять переводы не зависимо от разработчиков модификаций. Ко всему прочему, пакет ресурсов даёт возможность переводить модификации для старых версий Minecraft, которые в 99% случаев не будут обновляться разработчиками ради добавления перевода. Если лично вас не устраивает, что переводы делаются в таком формате, что ж, вы можете предлагать свои переводы для модификаций разработчикам, чтобы они сразу присутствовали в них. Но, как показывает практика 90% переводов модификаций в лучшем случае некорректны. Как бы то ни было, я продолжу переводить в таком формате, кому будет надо, те воспользуются переводами. Тема закрыта, если хотите продолжить диалог или задать ещё какой-либо вопрос, то делайте это в Discord сервере проекта, тут не место для такого рода дискуссий.
